pragma Singleton

import QtQuick
import Quickshell

Singleton {
    readonly property color base00: "#181818"
    readonly property color base01: "#282828"
    readonly property color base02: "#3c3836"
    readonly property color base03: "#504945"
    readonly property color base04: "#bdae93"
    readonly property color base05: "#d5c4a1"
    readonly property color base06: "#ebdbb2"
    readonly property color base07: "#fbf1c7"
    readonly property color base08: "#fb4934"
    readonly property color base09: "#fe8019"
    readonly property color base0A: "#fabd2f"
    readonly property color base0B: "#b8bb26"
    readonly property color base0C: "#8ec07c"
    readonly property color base0D: "#7daea3"
    readonly property color base0E: "#e089a1"
    readonly property color base0F: "#f28534"
    readonly property color disabledContainer: "#2f2e2a"
    readonly property color disabledContent: "#736b5c"
    readonly property color disabledOutline: "#413f38"
    readonly property color error: "#fb4934"
    readonly property color errorContainer: "#53251f"
    readonly property color inkError: "#181818"
    readonly property color inkErrorContainer: "#fb9576"
    readonly property color inkInverseSurface: "#181818"
    readonly property color inkPrimary: "#181818"
    readonly property color inkPrimaryContainer: "#b6ccb3"
    readonly property color inkSecondary: "#181818"
    readonly property color inkSecondaryContainer: "#bcd59c"
    readonly property color inkSuccess: "#181818"
    readonly property color inkSuccessContainer: "#d6d36e"
    readonly property color inkSurface: "#fbf1c7"
    readonly property color inkSurfaceVariant: "#bdae93"
    readonly property color inkTertiary: "#181818"
    readonly property color inkTertiaryContainer: "#ebb5b1"
    readonly property color inkWarning: "#181818"
    readonly property color inkWarningContainer: "#fdb367"
    readonly property color inverseSurface: "#ebdbb2"
    readonly property color outline: "#7c7164"
    readonly property color outlineVariant: "#504945"
    readonly property color primary: "#7daea3"
    readonly property color primaryContainer: "#34423f"
    readonly property color secondary: "#8ec07c"
    readonly property color secondaryContainer: "#374432"
    readonly property color success: "#b8bb26"
    readonly property color successContainer: "#3b3c1b"
    readonly property color surface: "#181818"
    readonly property color surfaceContainer: "#282828"
    readonly property color surfaceContainerHigh: "#363332"
    readonly property color surfaceContainerHighest: "#3c3836"
    readonly property color surfaceContainerLow: "#1f1f1f"
    readonly property color tertiary: "#e089a1"
    readonly property color tertiaryContainer: "#50383e"
    readonly property color warning: "#fe8019"
    readonly property color warningContainer: "#543318"
}
