export const GLYPHS = {
  back: "arrow_back",
  add: "add",
  agents: "smart_toy",
  codex: "robot_2",
  opencode: "code",
  shell: "terminal",
  folder: "folder_open",
  machine: "computer",
  project: "square",
  desktop: "desktop_windows",
  remove: "delete",
  notify: "notifications",
  notifyOff: "notifications_off",
  forward: "chevron_right",
  alert: "pan_tool",
  done: "check_circle",
  working: "progress_activity",
  idle: "pause_circle",
  offline: "wifi_off",
  signIn: "key",
  error: "error",
  check: "check",
}
